"""
GST Fraud Detection System
XGBoost Fraud Classifier
Phase 3 - Step 3
"""

import pandas as pd
import numpy as np
import os
import json
import pickle
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix,
    classification_report
)
import xgboost as xgb
import shap
import warnings
warnings.filterwarnings("ignore")

# ─────────────────────────────────────────
# STEP 1: Load the ML features CSV
# Generated by generate_data.py
# ─────────────────────────────────────────
def load_data():
    print("  Loading ml_features.csv...")
    base_dir      = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    features_path = os.path.join(base_dir, "data", "synthetic", "ml_features.csv")

    df = pd.read_csv(features_path)
    print(f"  Loaded {len(df):,} rows and {len(df.columns)} columns")
    print(f"  Fraud cases:  {df['is_fraud'].sum():,} ({df['is_fraud'].mean()*100:.1f}%)")
    print(f"  Normal cases: {(1-df['is_fraud']).sum():,} ({(1-df['is_fraud']).mean()*100:.1f}%)")
    return df


# ─────────────────────────────────────────
# STEP 2: Prepare features for ML
# Convert text columns to numbers
# ─────────────────────────────────────────
def prepare_features(df):
    print("\n  Preparing features...")

    # These are the columns we use to train
    # (not gstin, not fraud_type — those are identifiers/labels)
    FEATURE_COLUMNS = [
        "years_old", "annual_turnover",
        "filing_rate", "missing_returns", "avg_delay_days",
        "avg_itc_ratio", "total_itc_claimed", "total_tax_paid",
        "total_outward_supply", "avg_monthly_sales",
        "sales_volatility", "spike_ratio",
        "invoices_issued", "invoices_received", "invoice_match_rate",
        "unique_buyers", "unique_suppliers", "companies_same_address",
        "industry_encoded", "state_encoded", "size_encoded"
    ]

    # Encode text columns into numbers
    le_industry = LabelEncoder()
    le_state    = LabelEncoder()
    le_size     = LabelEncoder()

    df["industry_encoded"] = le_industry.fit_transform(df["industry"])
    df["state_encoded"]    = le_state.fit_transform(df["state_code"])
    df["size_encoded"]     = le_size.fit_transform(df["size_type"])

    X = df[FEATURE_COLUMNS]
    y = df["is_fraud"]

    print(f"  Features ready: {X.shape[1]} features for {X.shape[0]:,} GSTINs")

    # Save encoders for use in API later
    encoders = {
        "industry": le_industry,
        "state":    le_state,
        "size":     le_size,
        "feature_columns": FEATURE_COLUMNS
    }

    return X, y, encoders, df


# ─────────────────────────────────────────
# STEP 3: Split data into train and test sets
# 80% for training, 20% for testing
# ─────────────────────────────────────────
def split_data(X, y):
    print("\n  Splitting data: 80% train / 20% test...")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.2,
        random_state=42,
        stratify=y   # ensures same fraud % in both splits
    )

    print(f"  Training set: {len(X_train):,} rows")
    print(f"  Testing set:  {len(X_test):,} rows")
    print(f"  Train fraud%: {y_train.mean()*100:.1f}%")
    print(f"  Test fraud%:  {y_test.mean()*100:.1f}%")

    return X_train, X_test, y_train, y_test


# ─────────────────────────────────────────
# STEP 4: Train XGBoost Model
# scale_pos_weight handles imbalanced data
# (more normal than fraud cases)
# ─────────────────────────────────────────
def train_xgboost(X_train, y_train):
    print("\n  Training XGBoost model...")

    # Calculate class weight for imbalanced data
    fraud_count  = y_train.sum()
    normal_count = len(y_train) - fraud_count
    scale_weight = normal_count / fraud_count
    print(f"  Class weight (scale_pos_weight): {scale_weight:.2f}")

    model = xgb.XGBClassifier(
        # Tree parameters
        n_estimators      = 300,    # number of trees
        max_depth         = 6,      # depth of each tree
        learning_rate     = 0.05,   # how fast it learns
        subsample         = 0.8,    # % of rows per tree
        colsample_bytree  = 0.8,    # % of features per tree

        # Handles imbalanced fraud/normal ratio
        scale_pos_weight  = scale_weight,

        # Regularization (prevents overfitting)
        reg_alpha         = 0.1,
        reg_lambda        = 1.0,
        min_child_weight  = 5,

        # Performance
        use_label_encoder = False,
        eval_metric       = "auc",
        random_state      = 42,
        n_jobs            = -1,     # use all CPU cores
    )

    # Train with early stopping
    model.fit(
        X_train, y_train,
        eval_set        = [(X_train, y_train)],
        verbose         = False
    )

    print("  Training complete!")
    return model


# ─────────────────────────────────────────
# STEP 5: Evaluate model performance
# ─────────────────────────────────────────
def evaluate_model(model, X_test, y_test):
    print("\n" + "─" * 45)
    print("  MODEL PERFORMANCE REPORT")
    print("─" * 45)

    # Get predictions
    y_pred       = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]

    # Calculate all metrics
    accuracy  = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall    = recall_score(y_test, y_pred)
    f1        = f1_score(y_test, y_pred)
    auc_roc   = roc_auc_score(y_test, y_pred_proba)
    cm        = confusion_matrix(y_test, y_pred)

    print(f"\n  Accuracy:   {accuracy*100:.2f}%  (overall correct predictions)")
    print(f"  Precision:  {precision*100:.2f}%  (of flagged, how many are real fraud)")
    print(f"  Recall:     {recall*100:.2f}%  (of real fraud, how many we caught)")
    print(f"  F1 Score:   {f1*100:.2f}%  (balance of precision and recall)")
    print(f"  AUC-ROC:    {auc_roc:.4f}   (1.0 = perfect, 0.5 = random)")

    print(f"\n  Confusion Matrix:")
    print(f"  ┌─────────────────────────────────┐")
    print(f"  │              Predicted           │")
    print(f"  │          Normal    Fraud          │")
    print(f"  │ Actual Normal  {cm[0][0]:4d}      {cm[0][1]:4d}   │")
    print(f"  │ Actual Fraud   {cm[1][0]:4d}      {cm[1][1]:4d}   │")
    print(f"  └─────────────────────────────────┘")
    print(f"  True Negatives  (correct normal): {cm[0][0]}")
    print(f"  False Positives (wrongly flagged): {cm[0][1]}")
    print(f"  False Negatives (missed fraud):    {cm[1][0]}")
    print(f"  True Positives  (caught fraud):    {cm[1][1]}")

    # Cross validation for reliability
    print(f"\n  Running 5-fold cross validation...")
    cv_scores = cross_val_score(model, X_test, y_test, cv=5, scoring="roc_auc")
    print(f"  CV AUC scores: {[f'{s:.3f}' for s in cv_scores]}")
    print(f"  CV Mean AUC:   {cv_scores.mean():.4f} (+/- {cv_scores.std():.4f})")

    metrics = {
        "accuracy":  round(accuracy, 4),
        "precision": round(precision, 4),
        "recall":    round(recall, 4),
        "f1_score":  round(f1, 4),
        "auc_roc":   round(auc_roc, 4),
        "cv_mean_auc": round(cv_scores.mean(), 4),
    }

    return metrics, y_pred_proba


# ─────────────────────────────────────────
# STEP 6: Feature importance — what matters most?
# ─────────────────────────────────────────
def analyze_feature_importance(model, X_train, feature_names):
    print("\n" + "─" * 45)
    print("  TOP FRAUD DETECTION FEATURES")
    print("─" * 45)

    importance = model.feature_importances_
    feat_imp   = pd.DataFrame({
        "feature":    feature_names,
        "importance": importance
    }).sort_values("importance", ascending=False)

    print("\n  Rank  Feature                    Importance")
    print("  " + "-" * 42)
    for i, row in feat_imp.head(10).iterrows():
        bar   = "█" * int(row["importance"] * 200)
        print(f"  {feat_imp.index.get_loc(i)+1:2d}.   {row['feature']:<26} {row['importance']:.4f}  {bar}")

    return feat_imp


# ─────────────────────────────────────────
# STEP 7: SHAP — explain WHY each GSTIN was flagged
# ─────────────────────────────────────────
def generate_shap_explanation(model, X_test, feature_names, n_samples=3):
    print("\n" + "─" * 45)
    print("  SHAP EXPLANATIONS (Why flagged as fraud?)")
    print("─" * 45)

    explainer   = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_test)

    print(f"\n  Showing explanation for {n_samples} sample GSTINs:\n")

    for i in range(min(n_samples, len(X_test))):
        sample       = X_test.iloc[i]
        sample_shap  = shap_values[i]
        fraud_prob   = model.predict_proba(X_test.iloc[[i]])[0][1]

        risk_level = (
            "🔴 CRITICAL" if fraud_prob > 0.8 else
            "🟠 HIGH"     if fraud_prob > 0.6 else
            "🟡 MEDIUM"   if fraud_prob > 0.4 else
            "🟢 LOW"
        )

        print(f"  GSTIN Sample #{i+1}")
        print(f"  Fraud Probability: {fraud_prob*100:.1f}% — {risk_level}")
        print(f"  Top reasons:")

        shap_df = pd.DataFrame({
            "feature": feature_names,
            "shap":    sample_shap,
            "value":   sample.values
        }).sort_values("shap", key=abs, ascending=False)

        for _, row in shap_df.head(5).iterrows():
            direction = "↑ increases" if row["shap"] > 0 else "↓ decreases"
            print(f"    • {row['feature']:<26} = {row['value']:.3f}  {direction} fraud risk ({row['shap']:+.3f})")
        print()

    return explainer, shap_values


# ─────────────────────────────────────────
# STEP 8: Score ALL GSTINs and save results
# ─────────────────────────────────────────
def score_all_gstins(model, X, df):
    print("  Scoring all 5,000 GSTINs...")

    fraud_proba = model.predict_proba(X)[:, 1]
    predictions = model.predict(X)

    results_df = df[["gstin", "is_fraud", "fraud_type"]].copy()
    results_df["fraud_probability"] = (fraud_proba * 100).round(2)
    results_df["predicted_fraud"]   = predictions

    # Risk level labels
    def risk_label(prob):
        if prob >= 80: return "CRITICAL"
        if prob >= 61: return "HIGH"
        if prob >= 31: return "MEDIUM"
        return "LOW"

    results_df["risk_level"] = results_df["fraud_probability"].apply(risk_label)

    # Sort by highest risk first
    results_df = results_df.sort_values("fraud_probability", ascending=False)

    return results_df, fraud_proba


# ─────────────────────────────────────────
# STEP 9: Save model and results
# ─────────────────────────────────────────
def save_model_and_results(model, encoders, metrics, results_df, feat_imp):
    base_dir   = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    models_dir = os.path.join(base_dir, "src", "models", "saved")
    os.makedirs(models_dir, exist_ok=True)

    results_dir = os.path.join(base_dir, "data", "processed")
    os.makedirs(results_dir, exist_ok=True)

    # Save XGBoost model
    model_path = os.path.join(models_dir, "xgboost_fraud_model.json")
    model.save_model(model_path)

    # Save encoders
    enc_path = os.path.join(models_dir, "encoders.pkl")
    with open(enc_path, "wb") as f:
        pickle.dump(encoders, f)

    # Save metrics
    metrics_path = os.path.join(models_dir, "model_metrics.json")
    with open(metrics_path, "w") as f:
        json.dump(metrics, f, indent=2)

    # Save fraud scores for all GSTINs
    scores_path = os.path.join(results_dir, "fraud_scores.csv")
    results_df.to_csv(scores_path, index=False)

    # Save feature importance
    feat_path = os.path.join(results_dir, "feature_importance.csv")
    feat_imp.to_csv(feat_path, index=False)

    print(f"\n  Files saved:")
    print(f"    Model       → src/models/saved/xgboost_fraud_model.json")
    print(f"    Encoders    → src/models/saved/encoders.pkl")
    print(f"    Metrics     → src/models/saved/model_metrics.json")
    print(f"    Fraud scores→ data/processed/fraud_scores.csv")
    print(f"    Features    → data/processed/feature_importance.csv")


# ─────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────
def main():
    print("=" * 55)
    print("  GST FRAUD DETECTION - XGBOOST CLASSIFIER")
    print("=" * 55)

    print("\n[1/9] Loading data...")
    df = load_data()

    print("\n[2/9] Preparing features...")
    X, y, encoders, df = prepare_features(df)

    print("\n[3/9] Splitting train/test...")
    X_train, X_test, y_train, y_test = split_data(X, y)

    print("\n[4/9] Training XGBoost model...")
    model = train_xgboost(X_train, y_train)

    print("\n[5/9] Evaluating model...")
    metrics, y_pred_proba = evaluate_model(model, X_test, y_test)

    print("\n[6/9] Analyzing feature importance...")
    feat_imp = analyze_feature_importance(model, X_train, X.columns.tolist())

    print("\n[7/9] Generating SHAP explanations...")
    explainer, shap_values = generate_shap_explanation(
        model, X_test, X.columns.tolist(), n_samples=3
    )

    print("\n[8/9] Scoring all GSTINs...")
    results_df, all_proba = score_all_gstins(model, X, df)

    # Show top 10 high risk
    print("\n  TOP 10 HIGHEST RISK GSTINs:")
    print("  " + "─" * 55)
    print(f"  {'GSTIN':<20} {'Score':>6}  {'Risk':<10} {'Actual':<10} {'Type'}")
    print("  " + "─" * 55)
    for _, row in results_df.head(10).iterrows():
        actual = "FRAUD" if row["is_fraud"] == 1 else "NORMAL"
        print(f"  {row['gstin']:<20} {row['fraud_probability']:>5.1f}%  {row['risk_level']:<10} {actual:<10} {row['fraud_type']}")

    print("\n[9/9] Saving model and results...")
    save_model_and_results(model, encoders, metrics, results_df, feat_imp)

    # Final summary
    print("\n" + "=" * 55)
    print("  TRAINING COMPLETE!")
    print("=" * 55)
    print(f"\n  Final Model Performance:")
    print(f"    Accuracy:  {metrics['accuracy']*100:.2f}%")
    print(f"    Precision: {metrics['precision']*100:.2f}%")
    print(f"    Recall:    {metrics['recall']*100:.2f}%")
    print(f"    F1 Score:  {metrics['f1_score']*100:.2f}%")
    print(f"    AUC-ROC:   {metrics['auc_roc']:.4f}")

    critical = results_df[results_df["risk_level"] == "CRITICAL"]
    high     = results_df[results_df["risk_level"] == "HIGH"]
    medium   = results_df[results_df["risk_level"] == "MEDIUM"]
    low      = results_df[results_df["risk_level"] == "LOW"]

    print(f"\n  Risk Distribution across 5,000 GSTINs:")
    print(f"    🔴 CRITICAL  (>80%):  {len(critical):>4} GSTINs")
    print(f"    🟠 HIGH      (61-80%): {len(high):>4} GSTINs")
    print(f"    🟡 MEDIUM    (31-60%): {len(medium):>4} GSTINs")
    print(f"    🟢 LOW       (<30%):  {len(low):>4} GSTINs")

    print(f"\n  Next step: Build Anomaly Detection model (Isolation Forest)")
    print("=" * 55)


if __name__ == "__main__":
    main()